plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

group = "tech.graaf.franz.ar_flutter_plugin_plus"
version = "1.0-SNAPSHOT"

android {
    namespace = "tech.graaf.franz.ar_flutter_plugin_plus"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        targetSdk = 34
    }

    sourceSets {
        getByName("main").java.srcDirs("src/main/kotlin")
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = "21"
        languageVersion = "2.0"
    }

    buildFeatures {
        buildConfig = false
    }
}

dependencies {
    // Kotlin Runtime
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.1.0")

    // Google ARCore + Sceneform
    implementation("com.google.ar:core:1.51.0")
    implementation("com.google.ar.sceneform:core:1.17.1") {
        exclude group: "com.google.ar", module: "core"
    }
    implementation("com.google.ar.sceneform:assets:1.17.1") {
        exclude group: "com.google.ar", module: "core"
    }
    implementation("com.google.ar.sceneform.ux:sceneform-ux:1.17.1") {
        exclude group: "com.google.ar", module: "core"
    }   
    // AndroidX + Play Services
        // Sceneview for 3D capabilities
    implementation("io.github.sceneview:sceneview:2.3.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("com.google.android.gms:play-services-auth:20.7.0")
}

kotlin {
    jvmToolchain(21)
}
